name: 'Push To Registry'
description: 'This action allows you to push an image to Quay'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  image:
    description: 'Name of the image to push'
    required: true
  tag:
    description: 'Tag of the image to push'
    required: false
    default: 'latest'
  registry:
    description: 'Registry where to push the image (eg. quay.io/username)'
    required: true
  username:
    description: 'Username to use as credential to authenticate to the registry'
    required: true
  password:
    description: 'Password to use as credential to authenticate to the registry'
    required: true
outputs:
  image-url:
    description: 'Complete URL of the pushed image'
runs:
  using: 'node12'
  main: 'dist/index.js'
