name: 'Push To Registry'
description: 'Push a container image to an image registry'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  image:
    description: 'Name of the image to push'
    required: true
  tags:
    description: 'The tag or tags of the image to push. For multiple tags, seperate by a space. For example, "latest v1"'
    required: false
    default: 'latest'
  registry:
    description: 'Registry where to push the image (eg. quay.io/username)'
    required: true
  username:
    description: 'Username to use as credential to authenticate to the registry'
    required: true
  password:
    description: 'Password to use as credential to authenticate to the registry'
    required: true
  tls-verify:
    description: 'Verify TLS certificates when contacting the registry'
    required: false
    default: 'true'
  digestfile:
    description: | 
      After copying the image, write the digest of the resulting image to the file.
      By default, the filename will be determined from the image and tag.
      The contents of this file are the digest output.
    required: false
  extra-args:
    description: | 
      Extra args to be passed to podman push.
      Separate arguments by newline. Do not use quotes - @actions/exec will do the quoting for you.
    required: false
  
outputs:
  digest:
    description: 'The pushed image digest, as written to the "digestfile"'
  registry-paths:
    description: 'A JSON array of registry paths to which the tag(s) were pushed'
runs:
  using: 'node12'
  main: 'dist/index.js'
