name: 'Push To Registry'
description: 'This action allows you to push an image to Quay'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  image-to-push:
    description: 'Name of the new image that will be pushed'
    required: true
  tag:
    description: 'Tag of the new image'
    required: false
    default: 'latest'
  registry:
    description: 'Registry where to push the image (e.g quay.io/username)'
    required: true
  username:
    description: 'Username to use as credential to authenticate to the registry'
    required: true
  password:
    description: 'Password to use as credential to authenticate to the registry'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'