name: Link checker
on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      -'**.md'

jobs:
  markdown-link-check:
    name: Check links in markdown
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: true
