name: Link checker
on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  markdown-link-check:
    name: Check links in markdown
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: true
